name: cartao_visita
description: "A digital business card Flutter project"
publish_to: 'none' # impede publicação acidental no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # ícones estilo iOS
  url_launcher: ^6.1.10    # pacote para abrir links (GitHub, etc.)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0    # conjunto de regras de lint recomendadas

flutter:
  uses-material-design: true  # habilita ícones e widgets do Material Design
  assets:
    - assets/perfil.jpg       # caminho da imagem de perfil do cartão
